### PR TITLE
initial commit for the devcontainer configuration files

### PR DESCRIPTION
**Pull request by polographer**
This adds the necessary files to use the "dev container" feature on VSCode, which is helpful especially for M1 macs. It has everything it needs to be able to run RSpec and rubocop

### CODE REVIEW

**Review by markgoho — CHANGES_REQUESTED** [review]
@polographer I've done this for nearly every repo and this looks quite a bit different. Would you mind setting this up in a similar way?

For example, you should end up with:
image

and not just a devcontainer.json

Also, is this intended to only be used locally or in GitHub Codespaces?

**Comment by polographer** [comment]
> @polographer I've done this for nearly every repo and this looks quite a bit different. Would you mind setting this up in a similar way?
> 
> For example, you should end up with: image
> 
> and not just a devcontainer.json
> 
> Also, is this intended to only be used locally or in GitHub Codespaces?

Yes, I did it differently purposedly, instead of creating a Dockerfile that installs all the requirements manually I'm using a new feature of the devcontainer called [features](https://containers.dev/features) (touche) that augments the container instead of modifying it. 

For example, to install node, we have on the Dockerfile this;
```
# [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
ARG NODE_VERSION="none"
RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

```
and on postCreateCommand.sh these commands
```
bundle install
yarn install

```
all of this is replaced by this line (it installs nvm, yarn, and npm, note that node is installed via NVM) ;
```
		"ghcr.io/devcontainers/features/node:1": {"version":"14"},
```
the same thing happens with ruby. The docker file starts from the base image;
```
FROM mcr.microsoft.com/vscode/devcontainers/ruby:0-${VARIANT}
```
and then installs;
```
RUN gem install bundler -v 2.3.23
RUN gem update --system 3.3.26

```
all of this is replaced by: 
```		
"ghcr.io/devcontainers/features/ruby:1": {"version":"2.6.6"},
```
what it does, this installs RVM and then does internally an rvm install, similar to a developer environment.

Java in a similar fashion is installed via a dev tool called SDKMAN, and it's very easy to customize the distribution and the version. Switching to a redhat distribution should be very easy.
```
 {"version":"11", "distribution":"openjdk"},
```
The only one that I couldn't escape was libsodium, but I have started to read how to make my own features, that can potentially get rid of the apt install libsodium.

This should work on codespaces too.  The rebuilding doesn't take longer than rebuilding a container, 

I think is cleaner to use features than a custom Docker file because for example, it should be very easy to theorically swap the underlying distro and use redhat instead of debian. And most importantly we don't need to maintain the Dockerfile. If anything changes on the install the features (for example on some Dockerfiles I've seen that it downloads the node install) will change it for us.

**Comment by markgoho** [comment]
Okay I think there has been quite a bit of improvement to the process over the last number of months that I'm behind on.

I think the only concern between the features property and a Dockerfile is the difference between "knowledge in the head" and "knowledge in the world"

E.g. for the devcontainer setups with Dockerfile, it's very obvious what's being built and added to the environment because it references the Dockerfile and (beyond the base image) you can see what's happening. For the features, which very well could be the way we're headed, I think you just "have to know" what's happening there and that can lead to misunderstandings a less readable devcontainer setup.

Here's the Enroll devcontainer relevant parts:

``` json
"build": {
    "dockerfile": "Dockerfile",
    "args": {
      // Update 'VARIANT' to pick a Ruby version: 3, 3.1, 3.0, 2, 2.7, 2.6
      // Append -bullseye or -buster to pin to an OS version.
      // Use -bullseye variants on local on arm64/Apple Silicon.
      "VARIANT": "2.5",
      // Options
      "NODE_VERSION": "14"
    }
  },
```
and Dockerfile
``` Dockerfile
# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends libsodium23

# [Optional] Uncomment this line to install additional gems.
RUN gem install bundler -v 2.3.23

RUN gem update --system 3.3.26
```

To me (opinion) this is the preferable way to set things up because it doesn't rely too heavily on people knowing what `"ghcr.io/devcontainers/features/ruby:1": {"version":"2.6.6"},` does and it allows more customization (i.e. adding libsodium) to the environment.

**Comment by polographer** [comment]
Screen Shot 2023-01-31 at 10 26 31 AM

@markgoho I tested it on codespaces and it works, my proposal would be to merge as a start, and if it's not understood we can roll back to the Dockerfile approach

**Pull request merged**
