### PR TITLE
Refactor contract level validations for Applicant.

### PR DESCRIPTION
**Pull request by saikumar9**
ME-180551173

### CODE REVIEW

**Review by markgoho — DISMISSED** [review]
why aren't we using a revert commit?

**Comment by saikumar9** [comment]
> why aren't we using a revert commit?

I left the unit tests by making some modifications.

**Comment by markgoho** [comment]
revert has a specific meaning, if we're not reverting this commit, then please adjust the title to reflect the change more accurately

**Comment by saikumar9** [comment]
This will be handled in PR:https://github.com/ideacrew/aca_entities/pull/159

**Pull request closed without merging**
